http:
  routers:
    frontend:
      service: frontend
      rule: Host(`frontend.iberojet.unstract`)
    backend:
      service: backend
      rule: Host(`frontend.iberojet.unstract`) && PathPrefix(`/api/v1`, `/deployment`)

  services:
    frontend:
      loadBalancer:
        servers:
        # Point to service running on docker host.
        - url: http://host.docker.internal:3000/
        passHostHeader: true
    backend:
      loadBalancer:
        servers:
        # Point to service running on docker host.
        - url: http://host.docker.internal:8000/
        passHostHeader: true
